source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target "VENTouchLockSample" do
	pod 'VENTouchLock', :path => '../'
end

target "VENTouchLockSampleTests" do
  pod 'KIF', '~> 3.0.8'
end
